### ISSUE TITLE
Multiple line character bugs out PM space on Chrome

### ISSUE THREAD

**Issue by jacksbuilds** [xadamxk/HFX#103]
After entering the "newline character" specified in the PM section of the Chrome options, the output is such. Each character is added on a newline, as opposed to adding a newline at the designated point.

![askme](https://user-images.githubusercontent.com/24984165/29810716-c5ee0f94-8c55-11e7-8a3d-dcf6d106d330.png)

Edit: Updated grammar...1am writing wasn't great, at all.

**Comment by xadamxk** [comment]
@JNestler 
The PM feature you are referring to is called your 'PM Signature'.
If you would, post a screenshot of your PM Signature as it is displayed in the textbox of HFX.
Also, let me know which browser you are using, along with which HFX version you have installed.
Thank you

**Comment by Anxuein** [comment]
I am not able to replicate this and has not been any updates since last year. Can this be closed? @xadamxk
