### ISSUE TITLE
PM View Splits Messages

### ISSUE THREAD

**Issue by jacksbuilds** [xadamxk/HFX#104]
With a salutation and signature enabled, the PM view winds up looking something like this:
![pm](https://user-images.githubusercontent.com/24984165/29835621-6ddd26ee-8ca7-11e7-810c-9c2f9c040fbd.png)

I most definitely didn't send a PM with simply "Hey there." This occurs on the "Sent Mail" page, but seemingly not so when you open a PM in which the other user responded:

![image](https://user-images.githubusercontent.com/24984165/29835821-fe2ad1f6-8ca7-11e7-8264-54294830723f.png)

**Comment by xadamxk** [comment]
@JNestler 
I'm going to need you to explain this again for me.
Send me a message on HF and tell me how I need to respond to mimic this bug.
Thanks

**Comment by Anxuein** [comment]
I am not able to replicate this and has not been any updates since last year. Can this be closed? @xadamxk
