### ISSUE TITLE
Pressing Enter resets Character Count on Posts + PMs

### ISSUE THREAD

**Issue by jacksbuilds** [xadamxk/HFX#107]
When you press enter, the character counter is reset if you're writing a quick post. I have yet to test this on "full editing" mode, but it definitely occurs with quick post & PMs.

Google Chrome | 60.0.3112.113 (Official Build) (64-bit) (cohort: Stable)
HF Xtension: beta 0.0.2.1

**Comment by xadamxk** [comment]
Are you able to figure out what is causing this?
I've tried this one two different computers and my results are the same - it doesn't reset the character counter:

Below is a GIF:
https://i.imgur.com/amrYUAu.gif
