### ISSUE TITLE
Force Image HTTPS Bug

### ISSUE THREAD

**Issue by xadamxk** [xadamxk/HFX#43]
Current method will not work.
Need to search posts for MyCode image tags and convert them into a true HTML image tags.

**Comment by Anxuein** [comment]
Is force HTTPS needed now? When I've tried to add HTTP images, it gets made into HTTPS. @xadamxk

**Comment by xadamxk** [comment]
It depends on the host of the site. It will do it automatically with known hosts like imgur, but unknown hosts it doesn't. I can close this.
