### ISSUE TITLE
UserCP Email Toggle

### ISSUE THREAD

**Issue by xadamxk** [xadamxk/HFX#67]
Add setting to toggle email visibility.

**Comment by Anxuein** [comment]
Is this somewhere in UCP? I'm not sure what this is referring to. @xadamxk

**Comment by xadamxk** [comment]
Yes. It's below the username.

**Comment by Anxuein** [comment]
For Annoyance Fixer?

**Comment by xadamxk** [comment]
For now, yes.

**Comment by Anxuein** [comment]
In what category?

**Comment by xadamxk** [comment]
General for now. Might have to make a new instance on the manifest for only UserCP
