### ISSUE TITLE
Idea: Redesign PM Alerts

### ISSUE THREAD

**Issue by xadamxk** [xadamxk/HFX#71]
Talk with designers about concept.
Look at social media for notification/ banner examples.

**Comment by xadamxk** [comment]
@Anxuein How are you at designing?

**Comment by Anxuein** [comment]
I'm not good, honestly. I'm more backend.

**Comment by xadamxk** [comment]
As of MyBB 1.8, private messages remove quote chains by default, so this wouldn't be a very used feature.
