### ISSUE TITLE
LivePreview Bug: Fonts with spaces don't parse

### ISSUE THREAD

**Issue by xadamxk** [xadamxk/HFX#73]
Fix the space/dash issue with parsed fonts.

**Comment by Anxuein** [comment]
I don't understand this?

**Comment by xadamxk** [comment]
If you use a font that has a space in the title, it won't work when it's parsed by LivePreview.

**Comment by Anxuein** [comment]
Works fine with me in thread quickreply. Going into the main editor the live preview does not work at all?

**Comment by Anxuein** [comment]
@xadamxk I am not able to replicate this.

**Comment by xadamxk** [comment]
Another low priority bug.
